USE [master]
GO

/****** Object:  Database [Ton_403]    Script Date: 14.02.2024 10:31:08 ******/
DROP DATABASE [Ton_403]
GO

/****** Object:  Database [Ton_403]    Script Date: 14.02.2024 10:31:08 ******/
CREATE DATABASE [Ton_403]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ton_403', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Ton_403.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Ton_403_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Ton_403_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ton_403].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Ton_403] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Ton_403] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Ton_403] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Ton_403] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Ton_403] SET ARITHABORT OFF 
GO

ALTER DATABASE [Ton_403] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Ton_403] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Ton_403] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Ton_403] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Ton_403] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Ton_403] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Ton_403] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Ton_403] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Ton_403] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Ton_403] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Ton_403] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Ton_403] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Ton_403] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Ton_403] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Ton_403] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Ton_403] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Ton_403] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Ton_403] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Ton_403] SET  MULTI_USER 
GO

ALTER DATABASE [Ton_403] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Ton_403] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Ton_403] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Ton_403] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Ton_403] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Ton_403] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Ton_403] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Ton_403] SET  READ_WRITE 
GO

